name: terraform

on:

#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

  workflow_dispatch:

jobs:
  terraform_setup:
    runs-on: ubuntu-latest
    steps:
    
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

  terraform_init_validate:
    needs: terraform_setup
    runs-on: ubuntu-latest
    
    steps:
      #Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Dir root
        run: dir
      
      - name: chkdir
        run: cd ./AZ_Terraform
      
      - name: Dir AZ_Terraform
        run: dir
      
      - name: Terraform init
        working-directory: ./AZ_Terraform
        run: terraform init
