name: Veryfi_modules

on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          get-location
          Set-Location ./AZ_Terraform/
          
          $module_files = Get-ChildItem -Filter module*.tf

          foreach ($module_file in $module_files)
          {
              Write-Host "Przeszukuje plik: $module_file"
              $tf_module = Get-Content $module_file | Select-String -Pattern '"(module-\w+-\w+_\w+)"' | foreach {$_.Matches.Groups[1].Value}

              $module_file.BaseName

              if ($tf_module -eq $module_file.BaseName)
              {
                  Write-Host 'jest OK' -ForegroundColor Green
              }
              else
              {
                  Write-Host 'jest zle' -ForegroundColor Red
              }
          }

          $other_files = Get-ChildItem | where {($_.name -NotLike 'module*.tf') -and ($_.PSIsContainer -eq $False)}

          foreach ($other_file in $other_files)
          {
              $other_module = Get-Content $other_file | Select-String -Pattern 'module'

              $other_file.BaseName

             if (($other_module).count -gt 0)
             {
                 Write-Host 'Wykryto deklaracje innych modulow'
             }
             else
             {
                 Write-Host 'Jest OK'
             }
          }

        shell: pwsh 
